### ISSUE TITLE
when i join skyblock it just kicks me tf out (works if i toggle the diana stuff off)

### ISSUE THREAD

**Issue by Mauonfiksu** [Doppelclick/Diana#1]
![Minecraft 1 8 9 17 1 2024 16 24 37](https://github.com/Doppelclick/Diana/assets/156925268/c68cab5f-68be-41a7-a633-8c423726f654)

**Comment by Doppelclick** [comment]
Could you please send me a message on discord so I could help you properly?
If you cannot find my discord account, please run:
/msg user:558642345302687764 message:Hi!
In discord!
